#!/bin/sh

set -e

package="pictor"
webserver="apache2"

case "$1" in
	configure)
		chown www-data:www-data /var/cache/$package
		ln -sf /etc/$package/apache.conf /etc/$webserver/sites-available/$package
		a2ensite $package
		invoke-rc.d $webserver reload
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
